-- data to be deleted from uat oltp22

select count(*)
FROM STAGING_OWNER.STAGING_LOCAL_TO_PHOENIX_MAP
WHERE COUNTRY_CODE_TX LIKE '%AZ%KZ'; -- 27 rows

delete
FROM STAGING_OWNER.STAGING_LOCAL_TO_PHOENIX_MAP
WHERE COUNTRY_CODE_TX LIKE '%AZ%KZ';

commit;

select count(*)
FROM STAGING_OWNER.STAGING_LOCAL_TO_PHOENIX_MAP
WHERE COUNTRY_CODE_TX LIKE '%AZ%KZ';  -- 0 rows post delete

